<?php
/**
 * https://github.com/himanshubhaisare/ohShopify.php forked from cmcdonaldca/ohShopify.php
 */
require_once APP_PATH . '/library/shopify/shopify.php';
require_once APP_PATH . '/models/Product.php';
require_once APP_PATH . '/models/Variant.php';

$shopDomain = $this->config->shopify->shop_domain;
$apiKey     = $this->config->shopify->api_key;
$secret     = $this->config->shopify->secret;
$password   = $this->config->shopify->password;
$token      = "";
$response   = array();

// For private apps (you should never make private apps anyways):
$sc = new ShopifyClient($shopDomain, $token, $apiKey, $password, true);

try  {
    // Get all products
    $shopifyProducts = $sc->call('GET', '/admin/products.json', array('published_status'=>'published'));

    // Store products into stitchlite db
    foreach($shopifyProducts as $shopifyProduct) {
        $product       = new Product();
        $product->setProductName($shopifyProduct['title']);
        $product->setShopifyId($shopifyProduct['id']);
        $product->setType($shopifyProduct['product_type']);
        if ($product->create() == false) {
            $response[$shopifyProduct['id']] = "Can't save product {$shopifyProduct['sku']}";
        } else {
            $response[$shopifyProduct['id']] = "product {$shopifyProduct['title']} saved";
        }
        $shopifyVariants = $shopifyProduct['variants'];
        // Store variants into stitchlite db
        foreach($shopifyVariants as $shopifyVariant) {
            $variant       = new Variant();
            $variant->setProductName($shopifyVariant['title']);
            $variant->setSku($shopifyVariant['sku']);
            $variant->setPrice($shopifyVariant['price']);
            $variant->setQuantity($shopifyVariant['inventory_quantity']);
            $variant->setShopifyId($shopifyVariant['id']);
            $variant->setProductId($shopifyProduct['id']);
            if ($variant->create() == false) {
                $response[$shopifyVariant['id']] = "Can't save variant {$shopifyVariant['title']} of product {$shopifyProduct['title']}";
            } else {
                $response[$shopifyVariant['id']] = "variant {$shopifyVariant['title']} of product {$shopifyProduct['title']} saved";
            }
        }
    }

    echo '<pre>';
    print_r($response);
    echo '</pre>';

} catch (ShopifyApiException $e) {
    /*
     $e->getMethod() -> http method (GET, POST, PUT, DELETE)
     $e->getPath() -> path of failing request
     $e->getResponseHeaders() -> actually response headers from failing request
     $e->getResponse() -> curl response object
     $e->getParams() -> optional data that may have been passed that caused the failure

    */
    echo "Shopify Exception : method {$e->getMethod()}, path {$e->getPath()}, headers {$e->getResponseHeaders()}, response {$e->getReponse()}, params {$e->getParams()}";
} catch (ShopifyCurlException $e) {
    // $e->getMessage() returns value of curl_errno() and $e->getCode() returns value of curl_ error()
    echo "Curl Exception : method {$e->getMessage()}";
}