<?php
/**
 * https://github.com/himanshubhaisare/ohShopify.php forked from cmcdonaldca/ohShopify.php
 */
require_once APP_PATH . '/library/ohShopify/shopify.php';

$sc = new ShopifyClient($shop_domain, $token, $api_key, $secret);

// this is how to get the Authorize URL
$url = $sc->getAppInstallUrl();

// this is how you can check if the currrent request is authorized
$isAuthorized = $sc->isAppInstalled($timestamp, $sig);